### ISSUE TITLE
Python interface in Python 3 crashes with: has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by rubund** [thliebig/CSXCAD#11]
Hi,

The Python 2 interface seems to work well, but when building it for Python 3, it crashes like this:

```
>>> import CSXCAD
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/CSXCAD/__init__.py", line 7, in <module>
    from CSXCAD.CSXCAD import ContinuousStructure
  File "CSXCAD/CSXCAD.pyx", line 53, in init CSXCAD.CSXCAD
AttributeError: type object 'CSXCAD.CSXCAD.ContinuousStructure' has no attribute '__reduce_cython__'
>>> 
```

It would be nice to have a working Python 3 interface since Python 2 is soon End Of Life - and Python 3 is so much nicer.

**Comment by thliebig** [comment]
Thats surprising as I too use mainly Python 3. Can you please provide more infos about your distro, openEMS version, how you build and installed the python interface etc.?
Why is it installed under /usr/lib?

**Comment by rubund** [comment]
Hi Thorsten,

> Can you please provide more infos about your distro

Debian sid/unstable
cython3 version 0.29.2-2

> openEMS version

Latest and greatest GIT HEAD

> how you build and installed the python interface etc.?

cd CSXCAD/python
python3 setup.py build_ext
sudo python3 setup.py install

> Why is it installed under /usr/lib?

Because I am working on preparing the official Debian package of openEMS
with Python support - and I was testing that one before I submitted this
report.
But the same happens when I install in /usr/local/lib with a basic "sudo
python3 setup.py install"

I have not had time to dive down deeply to debug this issue.

Ruben

Den man. 11. feb. 2019 kl. 19:04 skrev Thorsten Liebig <
notifications@github.com>:

**Comment by thliebig** [comment]
Hmmm, for me it works fine using python3.7.2 with cython 0.29.3-1 on Manjaro Linux. But I only install without sudo like this:
python3 setup.py build_ext -I$HOME/opt/openEMS/include -L$HOME/opt/openEMS/lib -R$HOME/opt/openEMS/lib  install --user
Can you maybe try that? Otherwise I do not know how to reproduce or fix this issue...

**Comment by rubund** [comment]
Hi Thorsten,

Eventually I tracked down the solution to this problem.. **I had to install "python3-matplotlib"** :-)

That makes the error go away. It was very far more obvious by reading the error message. :)

Thank you.

Cheers
Ruben

**Comment by montanaviking** [comment]
Sadly, that didn't work for me. I updated matplotlib to no avail and get this same error message. Thanks

**Comment by montanaviking** [comment]
For me, CSXCAD import works fine but not openEMS
$ python3
>> import CSXCAD
>>> import openEMS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "openEMS/openEMS.pyx", line 26, in init openEMS.openEMS
AttributeError: type object 'openEMS.openEMS.openEMS' has no attribute '__reduce_cython__'
Thanks, Phil
